name: Cypress

on: [push, pull_request]

jobs:

  build-uberjar:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Clojure CLI
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.1.708.sh &&
        sudo bash ./linux-install-1.10.1.708.sh
    - name: Check versions
      run: |
        echo "Node.js `node --version`"
        echo "yarn `yarn --version`"
        java --version
        echo "Clojure `clojure -e "(println (clojure-version))"`"
        lein --version
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --lockfile
    - name: Get M2 cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
    - run: lein with-profile +include-all-drivers,+cloverage,+junit,+oss deps

    - name: Install gettext
      run: sudo apt install gettext
    - run: ./bin/build version
    - run: ./bin/build translations
    - run: ./bin/build frontend
    - run: ./bin/build drivers
    - run: ./bin/build uberjar

    - uses: actions/upload-artifact@v2
      with:
        name: uberjar
        path: './target/uberjar/metabase.jar'

  test-cypress-upgrade-v550-1:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    needs: build-uberjar
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      name: Retrieve uberjar artifact
      with:
        name: uberjar
    - name: Prepare uberjar
      run: |
        mkdir -p target/uberjar
        mv metabase.jar target/uberjar/
        ls -l target/uberjar/
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check versions
      run: |
        echo "Node.js `node --version`"
        echo "yarn `yarn --version`"
        java --version
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - run: ./bin/build version

    - run: yarn run test-cypress-no-build
      name: Run Cypress tests
      env:
        TERM: xterm

  test-cypress-upgrade-v550-2:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    needs: build-uberjar
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      name: Retrieve uberjar artifact
      with:
        name: uberjar
    - name: Prepare uberjar
      run: |
        mkdir -p target/uberjar
        mv metabase.jar target/uberjar/
        ls -l target/uberjar/
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check versions
      run: |
        echo "Node.js `node --version`"
        echo "yarn `yarn --version`"
        java --version
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - run: ./bin/build version

    - run: yarn run test-cypress-no-build
      name: Run Cypress tests
      env:
        TERM: xterm

  test-cypress-upgrade-v550-3:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    needs: build-uberjar
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      name: Retrieve uberjar artifact
      with:
        name: uberjar
    - name: Prepare uberjar
      run: |
        mkdir -p target/uberjar
        mv metabase.jar target/uberjar/
        ls -l target/uberjar/
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check versions
      run: |
        echo "Node.js `node --version`"
        echo "yarn `yarn --version`"
        java --version
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - run: ./bin/build version

    - run: yarn run test-cypress-no-build
      name: Run Cypress tests
      env:
        TERM: xterm

  test-cypress-upgrade-v550-4:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    needs: build-uberjar
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      name: Retrieve uberjar artifact
      with:
        name: uberjar
    - name: Prepare uberjar
      run: |
        mkdir -p target/uberjar
        mv metabase.jar target/uberjar/
        ls -l target/uberjar/
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check versions
      run: |
        echo "Node.js `node --version`"
        echo "yarn `yarn --version`"
        java --version
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - run: ./bin/build version

    - run: yarn run test-cypress-no-build
      name: Run Cypress tests
      env:
        TERM: xterm

  test-cypress-upgrade-v550-5:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    needs: build-uberjar
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      name: Retrieve uberjar artifact
      with:
        name: uberjar
    - name: Prepare uberjar
      run: |
        mkdir -p target/uberjar
        mv metabase.jar target/uberjar/
        ls -l target/uberjar/
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check versions
      run: |
        echo "Node.js `node --version`"
        echo "yarn `yarn --version`"
        java --version
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - run: ./bin/build version

    - run: yarn run test-cypress-no-build
      name: Run Cypress tests
      env:
        TERM: xterm
