name: Frontend Tests

on:
  pull_request:
    paths:
    - '**/frontend/**'
    - '!frontend/test/e2e/**'
    - '!**/*.cy.*'
    - '!**/*cypress*'
    - '!**/*.md'
    - 'shared/**'
    - '**/package.json'
    - '**/yarn.lock'
    - '.github/workflows/**'
  push:
    branches:
      - master
      - 'release**'
    tags:
      - '**'
    paths:
    - '**/frontend/**'
    - '!frontend/test/e2e/**'
    - '!**/*.cy.*'
    - '!**/*cypress*'
    - '!**/*.md'
    - 'shared/**'
    - '**/package.json'
    - '**/yarn.lock'
    - '.github/workflows/**'

jobs:

  fe-tests-unit:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile --prefer-offline
    - run: yarn run test-unit
      name: Run frontend unit tests

  fe-tests-timezones:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile --prefer-offline
    - run: yarn run test-timezones
      name: Run frontend timezones tests
